/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/animation/Animation.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    CardGroup: typeof import('./src/components/CardGroup.vue')['default']
    Carousel: typeof import('./src/components/ui/Carousel.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CodeRunner: typeof import('./src/components/CodeRunner.vue')['default']
    CodeRunnerGraph: typeof import('./src/components/CodeRunnerGraph.vue')['default']
    ColumnChart: typeof import('./src/components/visualize/ColumnChart.vue')['default']
    Console: typeof import('./src/components/ui/Console.vue')['default']
    ContentRender: typeof import('./src/components/ui/ContentRender.vue')['default']
    CourseReader: typeof import('./src/components/ui/CourseReader.vue')['default']
    CourseSelecter: typeof import('./src/components/CourseSelecter.vue')['default']
    DockPanel: typeof import('./src/components/layout/DockPanel.vue')['default']
    DockWidget: typeof import('./src/components/layout/DockWidget.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    EnterAnimation: typeof import('./src/components/animation/EnterAnimation.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    PaginationControl: typeof import('./src/components/ui/PaginationControl.vue')['default']
    PracticeReader: typeof import('./src/components/ui/PracticeReader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
